### ISSUE TITLE
unable to build the managarm.

### ISSUE THREAD

**Issue by Manish-Kala-Jaat** [managarm/managarm#73]
when building the managarm with the command - "xbstrap install --all"
it show error while building the gcc  , 
the error is =

xbstrap: build gcc [8/151]
xbstrap: Running ['make', 'all-gcc', 'all-target-libgcc', 'all-target-libstdc++-v3'] (tools: ['system-gcc', 'cross-binutils'])
Configuring in ./gmp
configure: loading cache ./config.cache
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `none-pc-managarm-system': machine `none-pc-managarm' not recognized
configure: error: /bin/bash /home/mak/Downloads/bootstrap-managarm-master/managram/build/../src/ports/gcc/gmp/config.sub none-pc-managarm-system failed
Makefile:4639: recipe for target 'configure-gmp' failed
make: *** [configure-gmp] Error 1
xbstrap: Action build of package gcc failed

**Comment by Manish-Kala-Jaat** [comment]
***screenshot***

![Screenshot (5546)](https://user-images.githubusercontent.com/49841018/57178566-19e08000-6e90-11e9-9ccb-15fa1c7779dd.png)

**Comment by avdgrinten** [comment]
Thank you for your report. I assume that your build OS is Ubuntu? What version of Ubuntu are you running? I will try to reproduce the issue.

**Comment by Manish-Kala-Jaat** [comment]
Ubuntu 18.04

**Comment by avdgrinten** [comment]
The GCC build requires some patch that bootstrap-managarm does not supply yet. As I plan to switch to GCC 9 in soon, I just disabled the GCC build for now. After pulling `bootstrap-managarm`, the build should work.

**Comment by avdgrinten** [comment]
This should be resolved now. Please re-open if it isn't.

**Comment by Manish-Kala-Jaat** [comment]
no way it is not solved yet , it shows -
xbstrap: Action regenerate of source eudev failed.

![Screenshot from 2019-05-16 17-50-27](https://user-images.githubusercontent.com/49841018/57853348-2c997400-7803-11e9-85b0-6db68ff9448f.png)

**Comment by avdgrinten** [comment]
Try to install `xsltproc` from Ubuntu's package repositories. I will update the bootstrap-managarm repository to list it as a dependency.

**Comment by Manish-Kala-Jaat** [comment]
again I tried one last time to build it, but it again giving initial problems -
xbstrap: build gcc [9/186]
xbstrap: Running ['make', 'all-gcc', 'all-target-libgcc', 'all-target-libstdc++-v3'] (tools: ['system-gcc', 'cross-binutils'])
Configuring in ./gmp
configure: loading cache ./config.cache
checking build system type... x86_64-pc-linux-gnu
checking host system type... Invalid configuration `none-pc-managarm-system': machine `none-pc-managarm' not recognized
configure: error: /bin/bash /home/mak/Downloads/managarm/build/../src/ports/gcc/gmp/config.sub none-pc-managarm-system failed
Makefile:4639: recipe for target 'configure-gmp' failed
make: *** [configure-gmp] Error 1
xbstrap: Action build of package gcc failed

=
i think it is due to the commit you made last day 
screenshot=
![Screenshot from 2019-05-24 08-41-58](https://user-images.githubusercontent.com/49841018/58300442-16417880-7e00-11e9-8ac0-e666540cfdcf.png)

**Comment by avdgrinten** [comment]
`gcc` should not be built by default. Do you specify it explicitly on the command line?

**Comment by Manish-Kala-Jaat** [comment]
No man I just did as given in the guide
